/** @type {import('prettier').Config} */
module.exports = {
    endOfLine: "lf",
    semi: false,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "es5",
    importOrder: [
      "^(react/(.*)$)|^(react$)",
      "^(react-dom/(.*)$)|^(react-dom$)",
      "<THIRD_PARTY_MODULES>",
      "",
      "^@gradient-bang/(.*)$",
      "",
      "^@/types/(.*)$",
      "^@",
      "",
      "^[./]",
    ],
    importOrderSeparation: false,
    importOrderSortSpecifiers: true,
    importOrderBuiltinModulesToTop: true,
    importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
    importOrderMergeDuplicateImports: true,
    importOrderCombineTypeAndValueImports: true,
    plugins: ["@ianvs/prettier-plugin-sort-imports"],
  }