#!/usr/bin/env python3
"""Generate strongly-typed helpers for the Gradient Bang server event schema."""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPO_ROOT / "schemas" / "server_events.schema.json"
PY_OUTPUT = REPO_ROOT / "schemas" / "generated_events.py"
TS_OUTPUT = REPO_ROOT / "client" / "src" / "schemas" / "serverEvents.ts"

PY_HEADER = "# Auto-generated by scripts/build_event_types.py.\n# Do not edit manually.\n"

TS_HEADER = "/* Auto-generated by scripts/build_event_types.py. */\n/* eslint-disable */\n"


def ensure_dirs() -> None:
    TS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)


def load_schema() -> dict:
    with SCHEMA_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def emit_python(schema: dict) -> None:
    event_names = schema["$defs"]["EventName"]["enum"]

    literal_items = ",\n".join(f"\"{name}\"" for name in event_names)
    literal_block = "    " + literal_items.replace("\n", "\n    ")
    tuple_items = ",\n".join(f"\"{name}\"" for name in event_names)
    tuple_block = "    " + tuple_items.replace("\n", "\n    ")

    content = f"""{PY_HEADER}
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Final, Literal, Sequence


_SCHEME_PATH: Final[Path] = Path(__file__).resolve().parent / "server_events.schema.json"


@lru_cache(maxsize=1)
def load_server_event_schema() -> Dict[str, Any]:
    '''Return a deep copy of the server event JSON schema.'''
    with _SCHEME_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


SERVER_EVENT_SCHEMA: Dict[str, Any] = load_server_event_schema()
SERVER_EVENT_NAMES: Final[Sequence[str]] = (
{tuple_block}
)
ServerEventName = Literal[
{literal_block}
]
"""

    with PY_OUTPUT.open("w", encoding="utf-8") as handle:
        handle.write(content)


def emit_typescript(schema: dict) -> None:
    event_names = schema["$defs"]["EventName"]["enum"]
    array_literal = ",\n  ".join(f"\"{name}\"" for name in event_names)

    content = (
        f"{TS_HEADER}"
        f"export const serverEventSchema = {json.dumps(schema, indent=2)} as const;\n\n"
        f"export const SERVER_EVENT_NAMES = [\n  {array_literal}\n] as const;\n\n"
        f"export type ServerEventName = typeof SERVER_EVENT_NAMES[number];\n"
    )

    with TS_OUTPUT.open("w", encoding="utf-8") as handle:
        handle.write(content)


def main() -> None:
    ensure_dirs()
    schema = load_schema()
    emit_python(schema)
    emit_typescript(schema)


if __name__ == "__main__":
    main()
