"""Protocol shared by all ``AsyncGameClient`` event-delivery adapters.

Adapters are constructed with a back-reference to an ``AsyncGameClient`` and
deliver events into it via a small documented surface area:

- ``client._request(endpoint, payload, ...)`` — HTTP/RPC to edge functions
  (used by the polling adapter to call ``events_since``).
- ``client._process_event(name, payload, request_id=...)`` — the dispatch
  sink defined in :class:`gradientbang.game.base_client.BaseAsyncGameClient`.
- ``client._maybe_update_sector_from_event(name, payload)`` — sector-cache
  update that respects the bound character's ownership guard.
- ``client._append_event_log(name, payload)`` — JSONL audit log.
- ``client._canonical_character_id`` — read for default scope filters.

Adapters MUST NOT touch any other private state on the client; the contract
above is the entire surface.
"""

from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class EventAdapter(Protocol):
    """Pluggable event-delivery transport for ``AsyncGameClient``."""

    async def purge_backlog(self) -> None:
        """Reset pending delivery before ``start``.

        Transport-specific. New startup code should prefer the explicit
        bootstrap lifecycle methods below.
        """
        ...

    async def prepare_bootstrap(self) -> None:
        """Prepare event delivery before bootstrap RPCs run.

        Session-queue pubsub registers its temporary queue here so event
        fanout cannot race ahead of queue creation. Polling transports may
        treat this as equivalent to ``purge_backlog``.
        """
        ...

    async def complete_bootstrap(self, discard_request_ids: set[str]) -> None:
        """Finish bootstrap without delivering queued startup echoes.

        Implementations should discard/archive messages whose request ids were
        generated by bootstrap RPCs and preserve unrelated messages for later
        catch-up replay.
        """
        ...

    async def replay_catchup(self) -> None:
        """Replay events buffered during bootstrap after the agent is active."""
        ...

    async def start(self) -> None:
        """Start delivering events. Idempotent — safe to call repeatedly."""
        ...

    async def stop(self) -> None:
        """Stop delivery and release any resources. Called from ``client.close()``."""
        ...

    def set_scope(
        self,
        *,
        character_ids: Optional[list[str]] = None,
        corp_id: Optional[str] = None,
        ship_ids: Optional[list[str]] = None,
    ) -> None:
        """Update the subscription scope.

        Each kwarg is independently applied:
        - ``character_ids`` replaces the character filter when non-empty after
          normalization. Passing an empty/whitespace-only list is a no-op.
        - ``ship_ids`` replaces the ship filter (corp pseudo-character ids).
        - ``corp_id`` is replaced unconditionally; ``None`` clears it.
        """
        ...

    async def sync_scope(self) -> None:
        """Persist any pending scope update before scoped event-emitting work."""
        ...
