# Auto-generated by scripts/build_event_types.py.
# Do not edit manually.

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Final, Literal, Sequence


_SCHEME_PATH: Final[Path] = Path(__file__).resolve().parent / "server_events.schema.json"


@lru_cache(maxsize=1)
def load_server_event_schema() -> Dict[str, Any]:
    '''Return a deep copy of the server event JSON schema.'''
    with _SCHEME_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


SERVER_EVENT_SCHEMA: Dict[str, Any] = load_server_event_schema()
SERVER_EVENT_NAMES: Final[Sequence[str]] = (
    "status.init",
    "status.update",
    "character.joined",
    "character.moved",
    "chat.message",
    "local_map",
    "warp.transfer",
    "warp.purchase",
    "port.reset",
    "port.regenerated",
    "tool_call",
    "tool_result",
    "task_output",
    "task_complete"
)
ServerEventName = Literal[
    "status.init",
    "status.update",
    "character.joined",
    "character.moved",
    "chat.message",
    "local_map",
    "warp.transfer",
    "warp.purchase",
    "port.reset",
    "port.regenerated",
    "tool_call",
    "tool_result",
    "task_output",
    "task_complete"
]
